research_task:
  description: >
    Find a list of jobs using the keyword "data scientist"
    Please use the Job Search tool provided rather than a web search.
  expected_output: >
    A list of job postings that contain the keyword "data scientist"
  agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
